# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
stages:
- stage: Deploy_Sample
  displayName: Sample - Deploy stage

  jobs:
  - deployment: Deploy
    variables:
    - name: image
      value: ${{parameters.containerRegistry}}/${{parameters.imageRepository}}
    displayName: Sample Deploy
    pool:
      vmImage: ${{parameters.vmImageName}}
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: ${{parameters.imagePullSecret}}
              dockerRegistryEndpoint: ${{parameters.dockerRegistryServiceConnection}}

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens'
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)/manifests/'
              targetFiles: 'deployment-sample.yml'
              keepToken: true
              tokenPrefix: __
              tokenSuffix: __
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(System.DefaultWorkingDirectory)/manifests/deployment-sample.yml
                $(System.DefaultWorkingDirectory)/manifests/service-sample.yml
              imagePullSecrets: |
                ${{parameters.imagePullSecret}}
              containers: |
                ${{parameters.containerRegistry}}/${{parameters.imageRepository}}:${{parameters.tag}}

